# Generated by Django 2.2.6 on 2021-06-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(blank=True, max_length=30, null=True)),
                ('equity', models.IntegerField(blank=True, null=True)),
                ('leverage', models.IntegerField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Hedged/Hedging', 'Hedged/Hedging'), ('Standart/Netted', 'Standart/Netted')], max_length=30, null=True)),
                ('select_pairs', models.CharField(blank=True, choices=[('AUD/USD', 'AUD/USD'), ('EUR/USD', 'EUR/USD')], max_length=30, null=True)),
                ('simulation_start_date', models.DateField(blank=True, max_length=10, null=True)),
                ('most_recent_data', models.BooleanField(blank=True, null=True)),
                ('tick_volume', models.BooleanField(blank=True, null=True)),
                ('min_timeframe', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
